LEARNING_RATE = 2e-3
LEARNING_RATE_DECAY = 0.97
LEARNING_RATE_DECAY_STEP = 10 # Decay after this many epochs
DECAY_RATE = 0.95
SEQ_LENGTH = 50
BATCH_SIZE = 50
ITERATIONS = 2000
GRAD_CLIP = 5
DATASET_PATH = "./datasets/nosleep.txt"

